### ISSUE TITLE
This username is already taken

### ISSUE THREAD

**Issue by Coriou** [Nukki/Melomania#1]
Hey - Wanted to try the demo. Impossible to register a new username because all the combinations I've tried return an "This username is already taken".

I've used random password generators, combinations of emojis and just smashed my keyboard, same thing.

Bug, or someone made a bot that just sent a `/create` request with every single possible combination just to prevent people playing the demo .. ?

**Comment by Nukki** [comment]
Hi @Coriou 

May I ask which browser( and version) you were using? 
As of today May 7, 2019 it did not give me a problem creating a user in Firefox, Safari and Chrome.
The screenshots below are from Chrome 74.0.3729.

<img width="575" alt="Screen Shot 2019-05-07 at 7 24 03 AM" src="https://user-images.githubusercontent.com/15151051/57295834-5a5f1a00-7099-11e9-997f-75889bb6fa19.png">
<img width="684" alt="Screen Shot 2019-05-07 at 7 24 20 AM" src="https://user-images.githubusercontent.com/15151051/57295837-6054fb00-7099-11e9-97c6-46c9ec67873e.png">

**Comment by Coriou** [comment]
Hey. Thanks for looking into this.

I've just tried again with Chrome & Safari, both worked on the first try.

I was using the same browsers last time. I did open the console see what was happening, and the server would consistently reply with an error about the username being already taken.

It doesn't seem to be the case anymore. Not sure what happened.

Thank you very much !
